### ISSUE TITLE
Map regions to default AMI ID

### ISSUE THREAD

**Issue by senderista** [uwescience/myria-ec2-ansible#10]
Currently we let users specify both AWS region and AMI ID to the `myria-deploy` script, but if they're launching into a non-default region (i.e., other than `us-west-2`) they have to manually look up the AMI for that region. This is tedious and error-prone, and since we only really support Ubuntu Server 14.04 amd64 HVM EBS SSD images, we should simply map each AWS region to a default AMI.

**Comment by BrandonHaynes** [comment]
+1 this would be great!

**Comment by senderista** [comment]
Fixed in https://github.com/uwescience/myria-ec2-ansible/commit/e4686d189c6a655033ea9de8ff113b8174f19cd6
