### ISSUE TITLE
myria-deploy fails with a couple complaints about Ansible

### ISSUE THREAD

**Issue by BrandonHaynes** [uwescience/myria-ec2-ansible#14]
The recent virtualenv change has broken execution for me (16c31f3de7f570125f6387c8e081cab3453ae8c2 works fine).  When running the following command:

```
./myria-deploy --region us-east-1 --instance-type t2.large --cluster-size 3 --ami-id ami-d05e75b8 --worker-mem-gb 6 --worker-vcores 2 --node-mem-gb 8 --node-vcores 2
```

I receive the following error:

```
Installing boto
myria-deploy: Ansible version must be 1.6+

Traceback (most recent call last):
  File "/usr/bin/ansible", line 36, in <module>
    from ansible.runner import Runner
ImportError: No module named ansible.runner
```

Ansible (1.9.3) is installed, so this is going to be a virtualenv thing.

**Comment by senderista** [comment]
@BrandonHaynes: should be fixed in https://github.com/uwescience/myria-ec2-ansible/commit/7198b35874b07e33a19395acafc1ed07c41ac1b4, please verify.

**Comment by senderista** [comment]
@BrandonHaynes closing since this should be fixed; please reopen if you're still hitting this issue.
