### ISSUE TITLE
Default output to verbose (and add silent switch)

### ISSUE THREAD

**Issue by BrandonHaynes** [uwescience/myria-ec2-ansible#26]
(Am I the only one who ALWAYS uses verbose mode?)

**Comment by senderista** [comment]
+1 I've noticed that new users always want as much output as possible, never the opposite. Just staring at a blank screen for half an hour while your giant cluster deploys isn't very reassuring.

**Comment by senderista** [comment]
fixed in d967ad493b507f3557a2d3b0334ac986ed65bce5
Now we have both `--silent` and `--verbose` switches. The default is semi-verbose (almost everything you currently see in verbose mode with a couple of omissions).
