### ISSUE TITLE
Ability to easily SSH among nodes within a cluster

### ISSUE THREAD

**Issue by jortiz16** [uwescience/myria-ec2-ansible#30]
Some example scripts that I had back when I used StarCluster. 

1) Using gnu parallels to run something like the following. What was nice was that I could use this script for any cluster I launched as long as I named my cluster the same each time I launched it:

```
host="mycluster-node001 mycluster-node002 mycluster-node003 mycluster-node004 mycluster-node005"

CMD="free && sync && echo \"echo 1 > /proc/sys/vm/drop_caches\" | sudo sh"
parallel -k --jobs +28 "/bin/echo -n '{} -- ' && ssh {} '$CMD'" ::: $host
```

2) This is another command I would often use, but I guess I could easily replace with SCP and the IP of the master. This command sends data from my local machine to the master node of my cluster:

```
starcluster put mycluster --node mycluster-master data /mnt/PSLAFolder
```

I think @parmitam had more?

**Comment by jortiz16** [comment]
Tagging people: @parmitam @senderista

**Comment by BrandonHaynes** [comment]
I had to manually enable this for the previous incarnation of the demo server, so I would find this feature useful as well.

**Comment by senderista** [comment]
@BrandonHaynes can you give examples of your dream syntax?

**Comment by BrandonHaynes** [comment]
Mostly stealing from StarCluster:

``` sh
myria-cluster ssh coordinator [cluster-name]
myria-cluster ssh workern [cluster-name]
myria-cluster scp [coordinator|workers] [source] [destination]
```

I had several cases where I needed to copy a file to ALL workers, so having that option would be nice.  I don't think I encountered a situation where I needed to copy to a single worker.  Others may have more use cases.

**Comment by BrandonHaynes** [comment]
Alternatively, we could just map from name to hostname in myria-cluster, and do everything externally:

```
ssh `myria-cluster get-hostname coordinator [cluster-name]`
```

This might avoid a proliferation of one-off shell commands inside the CLI.

**Comment by senderista** [comment]
I like the `myria-cluster get-coordinator-hostname [cluster-name]` idea; that would be about one line to implement. Although, `myria-cluster list` displays the coordinator hostname of each cluster, and  `myria-cluster list [cluster-name]` displays the hostnames of all nodes (where the coordinator always is assigned worker ID 0). Still, having it in a single command would simplify one-line shell commands like yours.

**Comment by BrandonHaynes** [comment]
Note that Jen and I both have had needs to get the hostnames for worker instances as well; that's why I made `coordinator`  separate argument (i.e., it could also be `worker-n`).

**Comment by senderista** [comment]
@BrandonHaynes unfortunately after supporting multiple workers/node we can no longer identify nodes by worker ID.

**Comment by BrandonHaynes** [comment]
Sure, then `node-n` instead :)

**Comment by senderista** [comment]
So how do we assign IDs to nodes, then--in the same order that we assign worker IDs? Wouldn't you need an extra lookup step to determine which node ID corresponded to a given worker ID? I guess we could add an extra `NODE_ID` column to the output of `myria-cluster list`--is something like that what you had in mind?

**Comment by BrandonHaynes** [comment]
My only use cases has involved (a) copying a file to every worker, or (b) SSHing into a broken worker to investigate a problem.  For either of these I don't care how they're numbered, so long as it is stable.

Adding a `NODE_ID` works for me, though I'd also be equally happy to just get a comma-separated list of all non-coordinator nodes that I could `cut` in scripts.

**Comment by senderista** [comment]
I've implemented a couple of new switches to the `myria-cluster list` command that output just the public hostnames of the coordinator and workers respectively:

```
myria-cluster list --coordinator my-test-cluster
myria-cluster list --workers my-test-cluster
```

This should be simple to use with shell one-liners:

```
$ c=0; for w in `myria-cluster list --region us-west-2 --workers my-test-cluster`; do echo "Worker $((++c)): $w"; done
Worker 1: ec2-54-218-60-60.us-west-2.compute.amazonaws.com
Worker 2: ec2-54-218-43-242.us-west-2.compute.amazonaws.com
```

**Comment by senderista** [comment]
fixed in 0e6bd20

**Comment by senderista** [comment]
So the main reason I see to create separate `myria-cluster` commands equivalent to `ssh` or `scp` is to take advantage of automatic private key handling. If you're willing to specify a private key file (which you would have to do anyway if you're not using the defaults), I don't see much advantage over just using the output of the new `list` commands with standard `ssh`/`scp` scripts. This is all user-driven, though, so I'd like feedback :)

**Comment by senderista** [comment]
@jortiz16 @BrandonHaynes closing for now, please reopen if the new options are inadequate for your needs.
