### ISSUE TITLE
Myria Service Restart Fails

### ISSUE THREAD

**Issue by jortiz16** [uwescience/myria-ec2-ansible#34]
When deploying an unprovisioned cluster, running a "sudo service myria restart" will fail to start up the service. According to the YARN node manager logs, it seems like the Myria user does not have permission to launch the application since it does not have write access to the /mnt/nm-local/ directory:

```
main : user is myria
main : requested yarn user is myria
Can't create directory /mnt/nm-local/usercache/myria/appcache/application_1470344511689_0005 - Permission denied
```

"myria restart" would work for me in the past, but I do not know what commit started causing this issue.

**Comment by senderista** [comment]
I've deployed an EC2 cluster with the `--unprovisioned` switch and both service restart (`sudo restart myria`) and cluster restart (`myria-cluster stop`/`myria-cluster start`) succeeded. Could you confirm this is still an issue?

**Comment by jortiz16** [comment]
Oh no, I will check again tomorrow morning and I'll make sure I have the latest version too! Thanks for looking into this.

**Comment by jortiz16** [comment]
Thanks Tobin, it seems to work now, so I'll close the issue. 

Not sure what happened last time (I tried launching several times and this would keep happening)
