### ISSUE TITLE
Myria-web contains invalid address in app.yml after attaching elastic IP

### ISSUE THREAD

**Issue by BrandonHaynes** [uwescience/myria-ec2-ansible#4]
After attaching an elastic IP, I had to update /mnt/myria-web/appengine/app.yml by setting MYRIAX_REST_HOST to the new IP.  Ideally this would be done automatically (somehow), but I'm documenting here for when it happens again.

**Comment by senderista** [comment]
I would like to avoid elastic IPs if possible. When launching a cluster in a default VPC, all instances get a public IP by default, so I don't see a good reason to use EIP unless we need it for an A record (which I guess is the case here). For public services, I'd prefer to run the cluster behind an ELB (for SSL termination, CloudWatch, etc.), in which case we only need a CNAME record to redirect to the ELB DNS name, and shouldn't need an EIP at all.
