### ISSUE TITLE
YARN logs are quickly filling up root volume

### ISSUE THREAD

**Issue by BrandonHaynes** [uwescience/myria-ec2-ansible#6]
YARN is logging about 1GB per day in /usr/local/hadoop-*/logs.  This exhausts the drive capacity for most instance types pretty quickly (it hosted the demo server over the weekend).  Either need to adjust the default granularity of logging or move them to the ephemeral drive.

**Comment by senderista** [comment]
What's the volume of YARN daemon logs compared to /opt/hadoop/logs/userlogs (i.e. container logs)?

**Comment by senderista** [comment]
Fixed in https://github.com/uwescience/myria-ec2-ansible/commit/0334549535920163dfe119fb2b437f7b391c5527
