### ISSUE TITLE
Launching in a new region clobbers existing key

### ISSUE THREAD

**Issue by BrandonHaynes** [uwescience/myria-ec2-ansible#9]
After happily running myria-deploy in us-west-2, I attempted to launch a cluster in us-east-1:

```
./myria-deploy --region us-east-1 --verbose
```

The myria-deploy script checked to see if the default key (`bhaynes-myria`) existed in the new region.  It didn't, and so the script deleted my existing key and created a new one:

```
A client error (InvalidKeyPair.NotFound) occurred when calling the DescribeKeyPairs operation: The key pair 'bhaynes-myria' does not exist
Creating new EC2 key pair bhaynes-myria
Deleting existing private key file /home/bhaynes/.ssh/bhaynes-myria.pem
Provisioning cluster...
```

This made me sad, because I really liked my existing key.

Suggest:

1) Rename a to-be-clobbered key (instead of deleting) so that I can recover it when something goes awry
2) Append the region to the default key name so that I can more easily maintain a default-key-per-region

**Comment by senderista** [comment]
Oops! Sorry about that, I hadn't thought about the cross-region clobbering behavior! Will implement your region-specific private key filename suggestion.

**Comment by senderista** [comment]
Fixed in https://github.com/uwescience/myria-ec2-ansible/commit/3bbc156e1908df63ca8158a6747a6c58550faf6e
